### ISSUE TITLE
可以支持Integer 类型吗?

### ISSUE THREAD

**Issue by feng-dan** [kamjin1996/mybatis-intercept-crypt#1]

**Comment by kamjin1996** [comment]
目前可以手动做个判断转换，回头考虑加个泛型支持

在 2021-03-04 10:58:28，Adrian ***@***.***> 写道：

**Comment by kamjin3086** [comment]
不支持的，因为int类型的数据，即使加密了数据库也没法存储

**Comment by feng-dan** [comment]
好的

发送自 Windows 10 版邮件应用

发件人: kamjin1996
发送时间: 2021年4月11日 15:51
收件人: kamjin1996/mybatis-intercept-crypt
抄送: Adrian; Author
主题: Re: [kamjin1996/mybatis-intercept-crypt] 可以支持Integer 类型吗? (#1)

不支持的，因为int类型的数据，即使加密了数据库也没法存储
